This programming exercise is from the textbook [Think Complexity, 2nd edition](https://thinkcomplex.com) by Allen Downey. This book is distributed under the [MIT License](http://opensource.org/licenses/MIT).

Some computer code from the textbook were also reused and modified for the purposes of this exercise. These reused computer code are indicated in the solution for this exercise and are still credited to the author.

# Solution goes here

The following code generates the code to be used for this exercise.

In [1]:
import numpy as np

"""
range(N) only returns an iterator
np.arange(N) has the same result as list(range(N))
"""


array = np.arange(8)
window = [1, 1, 1, 1]

print(array, window)

[0 1 2 3 4 5 6 7] [1, 1, 1, 1]


This is the version of correlate that has the same output as `numpy.correlate` except that it does not have the mode **full**. As hinted in the exercise, this uses the function `pad` from the `numpy` package.

In [2]:
"""
This returns a result that is similar to numpy.correlate except that it does not have the mode 'full'
Uses list comprehension to evaluate the elements of the array to be returned

The mode 'valid' returns the elements where the array and the window overlap

The mode 'same' returns an array with the same size as the input array

Other (undefined) modes will return a TypeError
Note that this is not robust in the sense that it does not check if the elements of the input arrays
are all floats or integers. This error however is caught by numpy.sum()
"""

def correlate(array, window, mode = 'valid'):
    window_len = len(window)
    array_len = len(array)
    
    original_size = array_len - window_len + 1
    
    # The initial conditional checks if the mode is a valid mode
    if mode == 'valid':
        c = [np.sum(array[k:k+window_len] * window) for k in range(original_size)]
        
        return np.array(c)
    
    elif mode == 'same':
        # This next conditional checks the amount of zeroes to be added to each side of the input array
        # For an odd number of zeroes, the left side will have an additional zero
        if (array_len - original_size) %2 == 1:
            resizer = (array_len - original_size - 1) // 2
            
            array = np.pad(array, (resizer+1, resizer), 'constant', constant_values = 0)
            c = [np.sum(array[k:k+window_len] * window) for k in range(array_len)]
            
            return np.array(c)
        
        # For an even number of zeroes, both sides will have the same number of zeroes
        elif (array_len - original_size) %2 == 0:
            resizer = (array_len - original_size) // 2
            
            array = np.pad(array, (resizer+1, resizer), 'constant', constant_values = 0)
            c = [np.sum(array[k:k+window_len] * window) for k in range(array_len)]
            
            return np.array(c)

    # Raises a TypeError if the input mode is undefined
    else:
        raise TypeError(mode + ' is an undefined mode')
    

print(correlate(array, window, 'same'))

[ 1  3  6 10 14 18 22 18]


In [3]:
"""
This is the result from numpy for comparison
"""

result = np.correlate(array, window, mode = 'same')
print(result)

[ 1  3  6 10 14 18 22 18]
